ITEM.Name =  "Box of Bolts";
ITEM.Desc =  "A box of bolts. Cheap and light, good for probing the path ahead.";
ITEM.Model =  "models/kali/miscstuff/stalker/bolt.mdl";
ITEM.Weight =  0;
ITEM.FOV =  4;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  0;
ITEM.W = 1
ITEM.H = 1
ITEM.License =  "X";
ITEM.Rarity = 0
ITEM.AllowRandomSpawn = true