ITEM.Name =  "Boots";
ITEM.Desc =  "A pair of boots. Musty, and conveniently just your size.";
ITEM.Model =  "models/kek1ch/boots.mdl";
ITEM.Weight =  0.6;
ITEM.License = "TX"
ITEM.SuitOnly = true
ITEM.RaiseCondition = 7
ITEM.FOV =  13;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.W = 2
ITEM.H = 2
ITEM.BulkPrice =  350
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true