ITEM.Name =  "Nice Boots";
ITEM.Desc =  "A nice, clean and unripped pair of boots. Conveniently just your size.";
ITEM.Model =  "models/kek1ch/boots.mdl";
ITEM.Weight =  0.6;
ITEM.License = "TX"
ITEM.SuitOnly = true
ITEM.RepairCondition = 10
ITEM.FOV =  13;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.W = 2
ITEM.H = 2
ITEM.BulkPrice =  1500;
ITEM.Rarity = 3
ITEM.AllowRandomSpawn = true