ITEM.Name = "Weapon Parts"
ITEM.Desc = "An assortment of gun parts."
ITEM.Model = "mmodels/kek1ch/waste_large.mdl"
ITEM.Weight = 0.5
ITEM.License = "T"
ITEM.BulkPrice =  12500;
ITEM.RaiseCondition = 25
ITEM.WeaponOnly = true
ITEM.W = 1
ITEM.H = 1