ITEM.Name = "Suit Parts"
ITEM.Desc = "A box of suit parts."
ITEM.Model = "models/props_lab/box01a.mdl"
ITEM.Weight = 0.5
ITEM.BulkPrice =  12500;
ITEM.RaiseCondition = 15
ITEM.SuitOnly = true
ITEM.W = 1
ITEM.H = 1