ITEM.Name = "Weapon Parts"
ITEM.Desc = "A box of gun parts."
ITEM.Model = "models/props_lab/box01a.mdl"
ITEM.Weight = 0.5
ITEM.License = "T"
ITEM.BulkPrice =  12500;
ITEM.RaiseCondition = 25
ITEM.WeaponOnly = true
ITEM.W = 1
ITEM.H = 1