ITEM.Name = "Suit Parts"
ITEM.Desc = "An assortment of suit parts."
ITEM.Model = "models/kek1ch/bron_k.mdl"
ITEM.Weight = 0.5
ITEM.BulkPrice =  12500;
ITEM.RaiseCondition = 15
ITEM.SuitOnly = true
ITEM.W = 1
ITEM.H = 1