ITEM.Name =  "PDA Encryption System";
ITEM.Desc =  "A custom FPGA with an unlocked CPU, no thermal limits and a chance of frying itself after use. The custom firmware on it is a derivative of VeraCrypt. Requires some specialist knowledge.";
ITEM.Model =  "models/stalker/item/handhelds/mini_pda.mdl";
ITEM.Weight =  0.5
ITEM.License = "T"
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.PhysicalMass	= 1;
ITEM.BulkPrice =  5000;
ITEM.W = 1
ITEM.H = 1