ITEM.Name =  "PDA Decryption System";
ITEM.Desc =  "A custom FPGA with an unlocked CPU, no thermal limits and extremely high chance of frying itself after use. Uses the latest in secret government research to defeat high level encryption. Requires some specialist knowledge.";
ITEM.Model =  "models/kek1ch/dev_decoder.mdl";
ITEM.Weight =  0.5;
ITEM.License = "T"
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.PhysicalMass	= 1;
ITEM.BulkPrice =  17500
ITEM.W = 1
ITEM.H = 1
ITEM.Rarity = 4
ITEM.AllowRandomSpawn = true