ITEM.Name =  "PDA Decryption System";
ITEM.Desc =  "A custom FPGA with an unlocked CPU, no thermal limits and extremely high chance of frying itself under load. Uses the latest in secret government research to defeat high level encryption. Requires some specialist knowledge.";
ITEM.Model =  "models/stalker/item/handhelds/mini_pda.mdl";
ITEM.Weight =  .5;
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.PhysicalMass	= 1;
ITEM.BulkPrice =  240000;
ITEM.W = 1
ITEM.H = 1