ITEM.Name =  "Scrap Metal";
ITEM.Desc =  "A pile of scrap metal.";
ITEM.Model =  "models/props_lab/box01a.mdl";
ITEM.Weight =  1;
ITEM.FOV =  13;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  50;
ITEM.RaiseCondition = 2;