ITEM.Name =  "Scrap Metal";
ITEM.Desc =  "A pile of scrap metal.";
ITEM.Model =  "models/kek1ch/psi_field.mdl";
ITEM.Weight =  1;
ITEM.FOV =  13;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  100
ITEM.License = "TX"
ITEM.RaiseCondition = 2
ITEM.W = 1
ITEM.H = 2
ITEM.Rarity = 1
ITEM.AllowRandomSpawn = true