ITEM.Name =  "Spool of Wire";
ITEM.Desc =  "A spool of thick fibers or wires utilized for equipment or electrical repair. Useful for the mechanically inclined.";
ITEM.Model =  "models/materials_wire.mdl";
ITEM.Weight =  0.2
ITEM.FOV =  15;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  500
ITEM.License =  "TX";
ITEM.RaiseCondition = 5
ITEM.W = 1
ITEM.H = 1
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true
