ITEM.Name =  "Antidote";
ITEM.Desc =  "An anti-toxin injection that absorbs and neutralizes natural poisons in the body.";
ITEM.Model =  "models/stalker/item/medical/antidote.mdl";
ITEM.Weight =  .1;
ITEM.FOV =  8;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.PhysicalMass	= 1;
ITEM.ConsumeText = "The antidote starts to clear toxins from your system. Over time, you start to become dehydrated."
ITEM.HealAmount = 0
ITEM.UseText = "Inject"
ITEM.BulkPrice =  1500;
ITEM.License =  "D";
ITEM.Rarity = 3
ITEM.AllowRandomSpawn = true