ITEM.Name =  "Anti-Rad Pills"
ITEM.Desc =  "A packet of anti-radiation drugs that neutralize radiation accumulated in the body."
ITEM.Model =  "models/kali/miscstuff/stalker/aid/anti-rad.mdl"
ITEM.Weight =  0.1
ITEM.FOV =  12
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice =  300
ITEM.License =  "D"
ITEM.UseText = "Consume"
ITEM.ConsumeText = "You slap the two pills into the back of your throat and swallow. After a while, you feel a tad dizzy and nauseous. You're suspicious whether or not they worked, but time confirms their effectivity for you."
ITEM.HealAmount = 0
ITEM.RadiationHealAmount = 20
ITEM.Rarity = 1
ITEM.AllowRandomSpawn = true