ITEM.Name =  "Gauze Bandages";
ITEM.Desc =  "A roll of gauze bandages. Used for emergency first aid.";
ITEM.Model =  "models/stalker/item/medical/bandage.mdl";
ITEM.ConsumeText = "You wrap the wound in bandages."
ITEM.HealAmount = 20
ITEM.Weight =  1;
ITEM.FOV =  9;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 5.02 );
ITEM.BulkPrice =  500;
ITEM.License =  LICENSE_BLACK;