ITEM.Name = "Skorpion"
ITEM.Desc = "An automatic Czech sidearm, useful for close encounters. Uses .32 ACP."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_vz61.mdl"
ITEM.WeaponClass = "tfa_mwr_vz61"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.15
ITEM.DegradeRate = 0.08
ITEM.FOV 			= 11;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "32acp"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 60000