ITEM.Name = "Colt 1911"
ITEM.Desc = "Quintessential american pistol. Won two world wars. Uses .45 ACP."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_m1911.mdl"
ITEM.WeaponClass = "tfa_mwr_m1911"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.17
ITEM.DegradeRate = 0.175
ITEM.FOV 			= 10;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "45acp"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 16000