ITEM.Name = "M92fs Beretta"
ITEM.Desc = "A tried and true pistol, adopted by army and police forces across the globe. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_m9.mdl"
ITEM.WeaponClass = "tfa_mwr_m9"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.17
ITEM.DegradeRate = 0.175
ITEM.FOV 			= 7;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 18000