ITEM.Name = "Spas 12"
ITEM.Desc = "A heavy police shotgun with the ability to fire in semi-auto or pump action.  Picky with it's ammo.  Has a cool folding stock but the gun itself is heavy and not optimal.  Uses 12 gauge."
ITEM.Model = "models/weapons/tfa_ins2/w_spas12_bri.mdl"
ITEM.WeaponClass = "tfa_ins2_spas12"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.09
ITEM.DegradeRate = 0.190
ITEM.FOV 			= 20;
ITEM.CamPos 		= Vector( 51.79, -8.92, 1.79 );
ITEM.LookAt 		= Vector( 17.68, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "12ga"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 50000