ITEM.Name = "PK-PSD9"
ITEM.Desc = "A pistol with an extended magazine in a bodykit for SMG ergonomics. Uses 9x19mmm."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_psd9.mdl"
ITEM.WeaponClass = "tfa_mwr_psd9"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.04
ITEM.DegradeRate = 0.12
ITEM.FOV 			= 14;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 1.61, -4.82, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 135000