ITEM.Name = "Mosin-Nagant"
ITEM.Desc = "Bolt action rifle of old. Not a sniper variant but still has it's massively long barrel. Uses 762x54R."
ITEM.Model = "models/weapons/tfa_ins2/w_mosin.mdl"
ITEM.WeaponClass = "tfa_ins2_mosin"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.04
ITEM.DegradeRate = 0.01
ITEM.FOV 			= 31;
ITEM.CamPos 		= Vector( 26.79, 100, 5.36 );
ITEM.LookAt 		= Vector( 11.25, 0, 0 );
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "762x39"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 28000