ITEM.Name = "Colt 9mm SMG"
ITEM.Desc = "An AR-15 in 9mm. A little bit rarer than most SMGs due to these not being as popular. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/w_m4_9mm.mdl"
ITEM.WeaponClass = "tfa_ins2_m4_9mm"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.03
ITEM.DegradeRate = 0.06
ITEM.FOV 			= 20;
ITEM.CamPos 		= Vector( 83.93, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 60000
