ITEM.Name = "Colt Anaconda"
ITEM.Desc = "A powerful .44 Magnum revolver, packs a punch."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_magnum.mdl"
ITEM.WeaponClass = "tfa_mwr_44mag"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.010
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 60
ITEM.AmmoType = "44mag"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 25000