ITEM.Name = "PKM"
ITEM.Desc = "Soviet GPMG. A terrifyingly powerful weapon, though heavy and unwieldy. Best used whilst braced. Fires 7.62x54R."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_pkm.mdl"
ITEM.WeaponClass = "tfa_mwr_pkm"
ITEM.Weight = 7
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.05
ITEM.DegradeRate = 0.010
ITEM.FOV 			= 20;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "762x54r"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 80000