ITEM.Name = "MP-443 Grach"
ITEM.Desc = "A newer Russian service pistol. Hard to find, but a handy sidearm. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/mp443/w_mp443.mdl"
ITEM.WeaponClass = "tfa_ins2_mp443"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.16
ITEM.DegradeRate = 0.09
ITEM.FOV 			= 9;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 15000