ITEM.Name = "PPSH-41"
ITEM.Desc = "Old SMG of the USSR. Fires a hail of pistol rounds. Not as common as other common weapons due to it's age. Uses 7.62x25mm."
ITEM.Model = "models/weapons/tfa_ins2/w_ppsh.mdl"
ITEM.WeaponClass = "tfa_ins2_ppsh"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.35
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 20;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "762x25"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 14000
