ITEM.Name = "SVD Dragunov"
ITEM.Desc = "The typical soviet semi-auto sniper. Not actually that accurate compared to other rifles, more of a DMR role. Uses 7.62x54R."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_dragunov.mdl"
ITEM.WeaponClass = "tfa_mwr_drag"
ITEM.Weight = 5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.05
ITEM.DegradeRate = 0.010
ITEM.FOV 			= 20;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "762x54r"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 175000