ITEM.Name = "Mk8 LMG"
ITEM.Desc = "A more modern LMG that takes box magazines. Somewhat accurate and puts out decent firepower. Quadstacked magazines are the hardest part of this gun to find.  Uses 5.56x45."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_mk8.mdl"
ITEM.WeaponClass = "tfa_mwr_mk8"
ITEM.Weight = 5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.08
ITEM.FOV 			= 20;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "556x45"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 80000