ITEM.Name = "Glock 17"
ITEM.Desc = "A very common striker fired pistol. Not quite as ubiquitous as the Makarov. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/w_glock17.mdl"
ITEM.WeaponClass = "tfa_ins2_glock17"
ITEM.Weight = 0.75
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.17
ITEM.DegradeRate = 0.175
ITEM.FOV 			= 8;
ITEM.CamPos 		= Vector( 12.5, 80.36, -5.35 );
ITEM.LookAt 		= Vector( 1.61, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 36000