ITEM.Name = "Makarov PM"
ITEM.Desc = "Most common pistol in the zone. Not in service but there's so many it overshadows even the Aks. Uses 9x18mm."
ITEM.Model = "models/weapons/w_pist_xoma_x4_pm.mdl"
ITEM.WeaponClass = "xoma_x4_pm"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.09
ITEM.DegradeRate = 0.012
ITEM.FOV 			= 7;
ITEM.CamPos 		= Vector( 50, -100, 1.79 );
ITEM.LookAt 		= Vector( -1.6, 1.61, -1.6 );
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "9x18"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 8000