ITEM.Name = "Mk 23"
ITEM.Desc = "An oversized .45 for Specialists or people who need to break necks when they pistol whip. Prefered by spies and Mercs."
ITEM.Model = "models/weapons/tfa_ins2/w_mk23.mdl"
ITEM.WeaponClass = "tfa_ins2_mk23"
ITEM.Weight = 1.25
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.17
ITEM.DegradeRate = 0.175
ITEM.FOV 			= 10;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "45acp"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 120000