ITEM.Name = "AK-74M"
ITEM.Desc = "A modernized AK-74 featuring an upgraded muzzle device and folding stock. Robust, and highly reliable, this weapon is preferred by experienced stalkers because of its familiar ergonomics and improved performance."
ITEM.Model = "models/weapons/tfa_ins2/w_ak74m.mdl"
ITEM.WeaponClass = "tfa_ins2_ak74m"
ITEM.Weight = 3.5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "545x39"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 73000