ITEM.Name = "MAC-10"
ITEM.Desc = "Made in the zone by various skilled stalkers. Fires a hail of .45 ACP."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_mac10.mdl"
ITEM.WeaponClass = "tfa_mwr_mac10"
ITEM.Weight = 2.75
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.09
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 13;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 4.83, 0, 0 );
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "45acp"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 45000