ITEM.Name = "Arsenal Firearms Strike One"
ITEM.Desc = "Russian designed, Italian made. This weapon is the go-to sidearm for Russian special forces. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_prokolot.mdl"
ITEM.WeaponClass = "tfa_mwr_prokolot"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.07
ITEM.DegradeRate = 0.8
ITEM.FOV 			= 9;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 50000