ITEM.Name = "KAM12"
ITEM.Desc = "Saiga-12 successor, rare automatic shotgun."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_kam12.mdl"
ITEM.WeaponClass = "tfa_mwr_kam12"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.06
ITEM.DegradeRate = 0.08
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "12ga"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 80000