ITEM.Name = "IMI Desert Eagle"
ITEM.Desc = "A huge hand cannon of a pistol, fires .50 AE. Maybe the user is compensating for something? Fires .50 Action Express."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_de50.mdl"
ITEM.WeaponClass = "tfa_mwr_de50"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.17
ITEM.DegradeRate = 0.2
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "50ae"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 90000