ITEM.Name = "Steyr M9-A1"
ITEM.Desc = "A devilishly handsome handgun from Austrian manufacturer Steyr. Its very sharp grip angle makes it point very well."
ITEM.Model = "models/smc/weapons/steyr-m9a1/w_steyr-m9a1.mdl"
ITEM.WeaponClass = "tfa_smc_m9a1"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 80000