ITEM.Name = "H&K G36"
ITEM.Desc = "At one time a state of the art assault rifle, the G36 is appearing with increased frequency in black market circles. 5.56x45mm."
ITEM.Model = "models/weapons/private_arsenals/w_g36.mdl"
ITEM.WeaponClass = "tfa_private_g36"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0003
ITEM.DegradeRate = 0.017
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 10, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_556x45"
ITEM.License = "B"
ITEM.BulkPrice = 89000
ITEM.Slot = 2
