ITEM.Name = "Stanley FuBar"
ITEM.Desc = "A multifunctional demolition device popular with people who like to break a variety of things in a variety of ways."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_fubar.mdl"
ITEM.WeaponClass = "tfa_nmrih_fubar"
ITEM.Weight = 10
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 40
ITEM.License = "X"
ITEM.BulkPrice = 9000
ITEM.Slot = 1
ITEM.Rarity = 4
ITEM.RepairCost = 1