ITEM.Name = "Benelli Nova"
ITEM.Desc = "An Italian hunting shotgun with a full-polymer construction. Lightweight and handy."
ITEM.Model = "models/weapons/tfa_ins2/w_nova.mdl"
ITEM.WeaponClass = "tfa_ins2_nova"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "12ga"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 50000