ITEM.Name = "IZH-43"
ITEM.Desc = "A full size double barrel hunting shotgun. Popular with rookies. Uses 12 gauge shells or slugs."
ITEM.Model = "models/weapons/tfa_ins2/w_doublebarrel.mdl"
ITEM.WeaponClass = "tfa_ins2_doublebarrel"
ITEM.Weight = 5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.015
ITEM.FOV 			= 10
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 10, 0, 0 )
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "B"
ITEM.BulkPrice = 27500
ITEM.Damage = 13
ITEM.Rarity = 2