ITEM.Name = "Meat Cleaver"
ITEM.Desc = "Rarely used for meal prep in the Zone, this meat cleaver is an intimidating sidearm that any rookie can afford."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_cleaver.mdl"
ITEM.WeaponClass = "tfa_nmrih_cleaver"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 40
ITEM.License = "A"
ITEM.BulkPrice = 3500
ITEM.Slot = 1
