ITEM.Name = "S&W 659"
ITEM.Desc = "A chrome (shine not included) pistol for the stalker more concerned with bling. Uses 9x19."
ITEM.Model = "models/weapons/tfa_ins2/w_sw659.mdl"
ITEM.WeaponClass = "tfa_ins2_sw659"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0008
ITEM.DegradeRate = 0.013
ITEM.FOV 			= 6;
ITEM.CamPos 		= Vector( 0, 100, 25 );
ITEM.LookAt 		= Vector( -0.5, 4, 0 );
ITEM.SelfRepairCondition = 90
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 61000
ITEM.TertiarySlot = true
ITEM.W = 2
ITEM.H = 1