ITEM.Name = "FN Five-seveN"
ITEM.Desc = "Placeholder description text! Report me."
ITEM.Model = "models/weapons/tfa_ins2/w_fn57.mdl"
ITEM.WeaponClass = "tfa_ins2_fiveseven"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "57x28"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 90000
ITEM.Slot = 2