ITEM.Name = "Walther P99"
ITEM.Desc = "A modern German pistol with excellent ergonomics. Slick and reliable. Uses 9x19mm"
ITEM.Model = "models/weapons/w_p99.mdl"
ITEM.WeaponClass = "tfa_walther_p99"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0003
ITEM.DegradeRate = 0.013
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 720000
ITEM.Slot = 2
