ITEM.Name = "AKS-74U"
ITEM.Desc = "A compact 5.45x39mm AK variant with a 4 inch barrel. Designed for use by paratroopers and tank crews, it is wildly popular among Stalkers operating in tunnels and caves."
ITEM.Model = "models/weapons/tfa_ins2/w_aks74u.mdl"
ITEM.WeaponClass = "tfa_ins2_aks74u"
ITEM.Weight = 3.5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0006
ITEM.DegradeRate = 0.0133
ITEM.FOV 			= 10
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 4, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_545x39"
ITEM.License = "B"
ITEM.BulkPrice = 80000
