ITEM.Name = "OTs-33 Pernach"
ITEM.Desc = "The Pernach is an automatic pistol designed to replace the Stechkin APS in various special units within the police, the ministry of internal affairs and other paramilitary units. Fires 9x18mm."
ITEM.Model = "models/weapons/w_ins2_pist_ots33.mdl"
ITEM.WeaponClass = "tfa_ins2_ots_33_pernach"
ITEM.Weight = 1.3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00014
ITEM.DegradeRate = 0.014
ITEM.FOV 			= 18;
ITEM.CamPos 		= Vector( 5, 37.5, 0 );
ITEM.LookAt 		= Vector( 4.6, 0, -2 );
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "ammo_9x18"
ITEM.License = "B"
ITEM.BulkPrice = 72500
ITEM.Slot = 2
ITEM.SlotPos = 1
ITEM.Damage = 33
ITEM.Rarity = 3
ITEM.RepairCost = 6