ITEM.Name = "Flare Gun"
ITEM.Desc = "Placeholder description text! Report me."
ITEM.Model = "models/weapons/w_monkflaregun.mdl"
ITEM.WeaponClass = "tfa_mats_flaregun"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "flare"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 10000
ITEM.Slot = 2