ITEM.Name = "L2A3 Sterling"
ITEM.Desc = "A British submachine gun of the 1950s. Despite its basic, even antiquated design, the hardy Sterling is still in use all over the world."
ITEM.Model = "models/weapons/tfa_ins2/w_sterling.mdl"
ITEM.WeaponClass = "tfa_ins2_sterling"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 60000