ITEM.Name = "MAC-10"
ITEM.Desc = "A classic crimegun popular with bandit bruisers and zombies. For some reason, it works best if held sideways. Chambered in .45  ACP."
ITEM.Model = "models/weapons/w_nam_mac10.mdl"
ITEM.WeaponClass = "tfa_nam_mac10"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.026
ITEM.FOV 			= 10
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 7, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "45acp"
ITEM.License = "B"
ITEM.BulkPrice = 60000
ITEM.Slot = 2
ITEM.Damage = 45