ITEM.Name = "Hammer"
ITEM.Desc = "A cheap household hammer. It'll do in a pinch."
ITEM.Model = "models/weapons/tfa_nmrih/w_tool_barricade.mdl"
ITEM.WeaponClass = "tfa_nmrih_bcd"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.01
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 50
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 2500