ITEM.Name = "MP5A3"
ITEM.Desc = "Popular 9mm German submachine gun from the Heckler & Koch firm. Reliable and easy to maintain; popular with rookies despite its price point."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_mp5.mdl"
ITEM.WeaponClass = "tfa_mwr_mp5"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 70000
ITEM.Slot = 2