ITEM.Name = "Browning Hi-Power"
ITEM.Desc = "One of the most widely used military pistols in history, this single-action, semi-automatic handgun was based on designs by John Browning, and later finished by FN Herstal. Uses 9x19mm."
ITEM.Model = "models/weapons/w_browninghp.mdl"
ITEM.WeaponClass = "tfa_browning_hp"
ITEM.Weight = 2.1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0004
ITEM.DegradeRate = 0.015
ITEM.FOV 			= 5
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1.75, 8, 0 )
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "ammo_9x19"
ITEM.License = "A"
ITEM.BulkPrice = 60000
ITEM.Slot = 2
ITEM.Damage = 33