ITEM.Name = "FN P90"
ITEM.Desc = "The Five-seveN's bigger bullpup cousin. A high RPM and armor-piercing round makes this PDW lethal in close quarters. Uses 5.7x28mm."
ITEM.Model = "models/weapons/tfa_ins2/w_mwr_p90.mdl"
ITEM.WeaponClass = "tfa_ins2_mwr_p90"
ITEM.Weight = 3.5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0003
ITEM.DegradeRate = 0.025
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( -4.5, 0, 0.5 )
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "ammo_57x28"
ITEM.License = "C"
ITEM.BulkPrice = 235000
ITEM.Slot = 2
