ITEM.Name = "SVT-40"
ITEM.Desc = "A Soviet battle rifle developed during the Second World War. Notorious for battering itself to death and intolerant of filth, but powerful and accurate. Uses 7.62x54mmR."
ITEM.Model = "models/weapons/tfa_ins2/w_svt40.mdl"
ITEM.WeaponClass = "tfa_ins2_svt40"
ITEM.Weight = 5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00119
ITEM.DegradeRate = 0.06
ITEM.FOV 			= 15;
ITEM.CamPos 		= Vector( 100, 100, 25 );
ITEM.LookAt 		= Vector( 10, 0, 0 );
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "ammo_762x54r"
ITEM.License = "B"
ITEM.BulkPrice = 142500
ITEM.Damage = 70
ITEM.Rarity = 3