ITEM.Name = "Uberti 1873 Peacemaker"
ITEM.Desc = "A modern copy of the Colt 1873 Peacemaker revolver. These replicas are un- or lightly-regulated in many European countries, so they often pop up in criminal circles. Chambered in .357 Magnum."
ITEM.Model = "models/weapons/tfre/w_peacemaker.mdl"
ITEM.WeaponClass = "tfa_tfre_colt_peacemaker"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "357mag"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 67500