ITEM.Name = "Ural Chainsaw"
ITEM.Desc = "A gas-powered chainsaw. Ideal for logging and serial killing."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_chainsaw.mdl"
ITEM.WeaponClass = "tfa_nmrih_chainsaw"
ITEM.Weight = 6
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.01
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 62500
ITEM.Slot = 1
ITEM.AmmoType = "gas"