ITEM.Name = "IZH-43"
ITEM.Desc = "An Izhevsk hunting shotgun with two side-by-side barrels. Uses 12 gauge."
ITEM.Model = "models/weapons/tfa_ins2/w_doublebarrel.mdl"
ITEM.WeaponClass = "tfa_ins2_doublebarrel"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.0143
ITEM.FOV 			= 9
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 7, 0, 0 )
ITEM.SelfRepairCondition = 45
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "B"
ITEM.BulkPrice = 18000
ITEM.Slot = 2
ITEM.Damage = 13
ITEM.Rarity = 2