ITEM.Name = "IZH-43 (sawn-off)"
ITEM.Desc = "An Izhevsk hunting shotgun with two side-by-side barrels. The barrels have been cut short for easy concealment. Uses 12 gauge."
ITEM.Model = "models/weapons/tfa_ins2/w_izh43_sawnoff.mdl"
ITEM.WeaponClass = "tfa_ins2_izh43sw"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.0143
ITEM.FOV 			= 9
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 7, 0, 0 )
ITEM.SelfRepairCondition = 45
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "A"
ITEM.BulkPrice = 23000
ITEM.Slot = 2
ITEM.Damage = 13