ITEM.Name = "Kimber Night Warrior"
ITEM.Desc = "A 1911 for the stalker or Merc wanting a bit more accuracy and modernity. Not a gun to be left unmaintained.  Uses .45 ACP."
ITEM.Model = "models/weapons/w_nb_ins_knw.mdl"
ITEM.WeaponClass = "tfa_ins2_knw"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0019
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 6;
ITEM.CamPos 		= Vector( 0, 100, 25 );
ITEM.LookAt 		= Vector( 1, 0, 0 );
ITEM.SelfRepairCondition = 90
ITEM.AmmoType = "ammo_45acp"
ITEM.License = "B"
ITEM.BulkPrice = 132500
ITEM.Damage = 45
ITEM.Rarity = 5