ITEM.Name = "SV-98"
ITEM.Desc = "A militarized version of the Record 300 precision sport rifle, the SV-98 is a highly accurate sniper rifle used for surgical work."
ITEM.Model = "models/weapons/ayykyu/sv_98/w_sv98.mdl"
ITEM.WeaponClass = "tfa_ayykyu_sv98"
ITEM.Weight = 5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "762x54"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 255000