ITEM.Name = "AKM"
ITEM.Desc = "The classic Russian assault rifle. Tried and true, used all across the world. Uses 7.62x39mm"
ITEM.Model = "models/weapons/tfa_ins2/w_akm.mdl"
ITEM.WeaponClass = "tfa_ins2_akm"
ITEM.Weight = 5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.013
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 6, 0, 0 )
ITEM.SelfRepairCondition = 65
ITEM.AmmoType = "ammo_762x39"
ITEM.License = "B"
ITEM.BulkPrice = 83000
ITEM.Damage = 42
ITEM.Rarity = 2