ITEM.Name = "Benelli Nova"
ITEM.Desc = "An Italian hunting shotgun with a full-polymer construction. Lightweight and handy. Uses 12 gauge."
ITEM.Model = "models/weapons/tfa_ins2/w_nova.mdl"
ITEM.WeaponClass = "tfa_ins2_nova"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0008
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 15, 0, 0 )
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "12ga"
ITEM.License = "B"
ITEM.BulkPrice = 60000
ITEM.Slot = 2
