ITEM.Name = "Fort 500"
ITEM.Desc = "A Ukrainian police shotgun. Rugged and reliable, and inexpensive to maintain thanks to domestic manufacture. Twelve gauge."
ITEM.Model = "models/props_junk/cardboard_box003a.mdl"
ITEM.WeaponClass = "tfa_ins2_fort500"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 55000
ITEM.Slot = 2