ITEM.Name = "H&K MP7A1"
ITEM.Desc = "A personal defense weapon from Germany. Extremely compact and intended for both one or two handed firing stances."
ITEM.Model = "models/props_lab/box01a.mdl"
ITEM.WeaponClass = "tfa_fml_wheresacog"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "46x30"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 65000