ITEM.Name = "Pickaxe"
ITEM.Desc = "A top heavy digging implement for breaking up rocks and dirt."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_pickaxe.mdl"
ITEM.WeaponClass = "tfa_nmrih_pickaxe"
ITEM.Weight = 6
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.03
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.License = "A"
ITEM.BulkPrice = 3500
ITEM.Slot = 1
