ITEM.Name = "Colt M1911"
ITEM.Desc = "An old-school, .45 ACP, hard hitter. Intimidating and powerful, but sorely outdated and hindered by its small magazine."
ITEM.Model = "models/weapons/tfa_ins2/w_m1911.mdl"
ITEM.WeaponClass = "tfa_ins2_m1911"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "45acp"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 65000
ITEM.Slot = 2