ITEM.Name = "Remington 870"
ITEM.Desc = "A pump-action shotgun manufactured by Remington. Used in hunting game or - more popularly in the Zone - people. Uses a variety of 12 gauge shells."
ITEM.Model = "models/weapons/w_remington_m870.mdl"
ITEM.WeaponClass = "tfa_remington_m870"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.014
ITEM.FOV 			= 8
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 10, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "12ga"
ITEM.License = "A"
ITEM.BulkPrice = 75000
ITEM.Slot = 2
