ITEM.Name = "Makarov PM"
ITEM.Desc = "A ubiquitous 9x18 sidearm used in military, police, and civillian applications since the Iron Curtain. While highly reliable, its weight and low magazine capacity have relegated it to rear line status."
ITEM.Model = "models/weapons/w_pist_xoma_x4_pm.mdl"
ITEM.WeaponClass = "xoma_x4_pm"
ITEM.Weight = 1.2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00011
ITEM.DegradeRate = 0.012
ITEM.FOV 			= 6;
ITEM.CamPos 		= Vector( 0, -100, 25 );
ITEM.LookAt 		= Vector( 0, -5, 0 );
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "ammo_9x18"
ITEM.License = "A"
ITEM.BulkPrice = 24000
ITEM.Slot = 2
ITEM.SlotPos = 1
