ITEM.Name = "GSh-18"
ITEM.Desc = "A Russian pistol designed to handle extreme overpressure rounds. Mechanically complex, this pistol requires more maintenance than normal to remain reliable."
ITEM.Model = "models/weapons/w_gsh18.mdl"
ITEM.WeaponClass = "tfa_ins2_gsh18"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 72500