ITEM.Name = "IMI Desert Eagle (.357)"
ITEM.Desc = "The eighties called - they want their gun back. Chambered in .357 Magnum."
ITEM.Model = "models/weapons/tfa_ins2/w_deagle.mdl"
ITEM.WeaponClass = "tfa_ins2_deagle"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00021
ITEM.DegradeRate = 0.015
ITEM.FOV 			= 7;
ITEM.CamPos 		= Vector( 0, 100, 25 );
ITEM.LookAt 		= Vector( 1.5, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "ammo_357mag"
ITEM.License = "B"
ITEM.BulkPrice = 136000
ITEM.Damage = 65