ITEM.Name = "PPSH-41"
ITEM.Desc = "Old SMG of the USSR. Fires a hail of pistol rounds. Not as common as other common weapons due to it's age. Uses 7.62x25mm."
ITEM.Model = "models/weapons/tfa_ins2/w_ppsh.mdl"
ITEM.WeaponClass = "tfa_ins2_ppsh"
ITEM.Weight = 2.9
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0011
ITEM.DegradeRate = 0.022
ITEM.FOV 			= 8;
ITEM.CamPos 		= Vector( 100, 100, 25 );
ITEM.LookAt 		= Vector( 1, 0, 0 );
ITEM.SelfRepairCondition = 65
ITEM.AmmoType = "762x25"
ITEM.License = "B"
ITEM.BulkPrice = 55000
ITEM.Damage = 31
