ITEM.Name = "Dragunov Sniper Rifle"
ITEM.Desc = "A venerable sniper rifle of Soviet origin. Standard issue for many Eastern militaries, and often copied. Uses 7.62x54mmR."
ITEM.Model = "models/weapons/tfa_ins2/w_svd.mdl"
ITEM.WeaponClass = "tfa_ins2_svd"
ITEM.Weight = 7
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00024
ITEM.DegradeRate = 0.013
ITEM.FOV 			= 8
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 5, 0, 2 )
ITEM.SelfRepairCondition = 65
ITEM.AmmoType = "762x54r"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 210000
ITEM.Slot = 2
ITEM.NoDefaultAtts = true
