ITEM.Name = "SKS"
ITEM.Desc = "A semi-automatic carbine that started production shortly after WW2, but didn't see major use in favour of the AK-47. Uses 7.62x39mm."
ITEM.Model = "models/weapons/tfa_ins2/w_sks.mdl"
ITEM.WeaponClass = "tfa_ins2_sks"
ITEM.Weight = 3.25
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0008
ITEM.DegradeRate = 0.018
ITEM.FOV 			= 15;
ITEM.CamPos 		= Vector( 100, 100, 25 );
ITEM.LookAt 		= Vector( 5, 0, 0 );
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_762x39"
ITEM.License = "B"
ITEM.BulkPrice = 70000
