ITEM.Name = "Pipe Wrench"
ITEM.Desc = "A heavy plumber's tool that can easily cave in a skull and is practically unbreakable."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_wrench.mdl"
ITEM.WeaponClass = "tfa_nmrih_wrench"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.01
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 50
ITEM.License = "A"
ITEM.BulkPrice = 3500
ITEM.Slot = 1
