ITEM.Name = "VHS-D2"
ITEM.Desc = "First introduced in 2007 for the Croatian Army, this NATO bullpup assault rifle strongly resembles the french FAMAS rifle, but functions and dissassembles much differently. Uses 5.56x45mm."
ITEM.Model = "models/weapons/tfa_ins2_vhsd2/w_m4a1.mdl"
ITEM.WeaponClass = "tfa_ins2_vhsd2"
ITEM.Weight = 3.3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0004
ITEM.DegradeRate = 0.014
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "556x45"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 145000
ITEM.Slot = 2
