ITEM.Name = "Aluminum Bat"
ITEM.Desc = "An aluminum baseball bat. You can't think of any local baseball teams."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_bat_metal.mdl"
ITEM.WeaponClass = "tfa_nmrih_bat"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.22
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 65
ITEM.License = "X"
ITEM.BulkPrice = 2500
ITEM.Slot = 1
ITEM.Rarity = 1
ITEM.AllowRandomSpawn = true
ITEM.RepairCost = 1