ITEM.Name = "TOZ"
ITEM.Desc = "A full size double barrel hunting shotgun. Popular with rookies. Uses 12 gauge shells or slugs."
ITEM.Model = "models/weapons/tfa_ins2/w_doublebarrel.mdl"
ITEM.WeaponClass = "tfa_ins2_doublebarrel"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.08
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "12ga"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 42000
