ITEM.Name = "Smith & Wesson Safety Hammerless"
ITEM.Desc = "An antiquated pocket revolver that can still be found in criminal circles all over Europe. Unbelievably tiny and chambered in the wimpy .32 Short & Weak."
ITEM.Model = "models/weapons/tfre/w_hammerless.mdl"
ITEM.WeaponClass = "tfa_tfre_hammerless"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "32acp"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 20000
ITEM.Slot = 2