ITEM.Name = "CZ 75B"
ITEM.Desc = "A Czech pistol in use by several law enforcement agencies and militaries. Dependable. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/w_cz75b.mdl"
ITEM.WeaponClass = "tfa_ins2_cz75"
ITEM.Weight = 1.75
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.16
ITEM.FOV 			= 6;
ITEM.CamPos 		= Vector( 0, 100, 25 );
ITEM.LookAt 		= Vector( 1, 0, 0 );
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "9x19"
ITEM.License = "A"
ITEM.BulkPrice = 45000
