ITEM.Name = "Daewoo K2"
ITEM.Desc = "Developed by the South Korean Agency for Defense Development and manufactured by S&T Motiv, the K2 has become the service rifle of the Republic of Korea Armed Forces. Fires 5.56x45mm."
ITEM.Model = "models/weapons/w_k2.mdl"
ITEM.WeaponClass = "tfa_ins_daewoo_k2"
ITEM.Weight = 3.55
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0004
ITEM.DegradeRate = 0.012
ITEM.FOV 			= 23;
ITEM.CamPos 		= Vector( 0, 90, 0 );
ITEM.LookAt 		= Vector( 8, 0, 2 );
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "ammo_556x45"
ITEM.License = "B"
ITEM.BulkPrice = 297500
ITEM.Slot = 2
ITEM.Damage = 35
ITEM.Rarity = 5
ITEM.RepairCost = 23