ITEM.Name = "Dragunov Sniper Rifle"
ITEM.Desc = "A venerable sniper rifle of Soviet origin. Standard issue for many Eastern militaries, and often copied."
ITEM.Model = "models/weapons/tfa_ins2/w_svd.mdl"
ITEM.WeaponClass = "tfa_ins2_svd"
ITEM.Weight = 5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "762x54"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 190000
ITEM.Slot = 2
ITEM.NoDefaultAtts = true