ITEM.Name = "H&K USP 45"
ITEM.Desc = "An accurate and ultra-reliable polymer pistol chambered in .45 ACP. A bit hefty, though."
ITEM.Model = "models/weapons/tfa_ins2/w_usp45.mdl"
ITEM.WeaponClass = "tfa_ins2_usp45"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0001
ITEM.DegradeRate = 0.021
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_45acp"
ITEM.License = "B"
ITEM.BulkPrice = 75000
ITEM.Slot = 2
ITEM.Damage = 45
ITEM.Rarity = 3
ITEM.RepairCost = 6
ITEM.Vars = {
	Equipped = false,
	CurrentAttachments = {},
	Upgrades = {
        generic_opt_mount = true,
		generic_underbarrel_mount = true,
	},
	Durability = 100,
	Clip1 = 0,
},