ITEM.Name = "Fire Axe"
ITEM.Desc = "A heavy axe for forced entry into burning buildings. Not especially picky about what it's entering."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_axe_fire.mdl"
ITEM.WeaponClass = "tfa_nmrih_fireaxe"
ITEM.Weight = 6
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 40
ITEM.License = "A"
ITEM.BulkPrice = 20000
ITEM.Slot = 1
