ITEM.Name = "Glock 19"
ITEM.Desc = "A popular handgun for police, military and civilian applications the world around. Versatile and rugged. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/w_glock19.mdl"
ITEM.WeaponClass = "tfa_ins2_glock_19"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1, 0, 0 )
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "9x19"
ITEM.License = "B"
ITEM.BulkPrice = 65000
ITEM.Slot = 2
ITEM.TertiarySlot = true
ITEM.W = 2
ITEM.H = 1
