ITEM.Name = "KA-BAR"
ITEM.Desc = "Service with a smile since 1942. Can be fashioned into a spear using the loop on the crossguard."
ITEM.Model = "models/weapons/tfa_ins2/w_marinebayonet.mdl"
ITEM.WeaponClass = "tfa_ins2_kabar"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.1
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 40
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 15000
ITEM.Slot = 1
ITEM.TertiarySlot = true
ITEM.W = 1
ITEM.H = 2