ITEM.Name = "Mauser C96"
ITEM.Desc = "One of the earliest semi-automatic pistols to find success on the open market. A relic which commands a premium due to collector interest. Due to a lifetime of neglect, this example is somewhat finicky no matter what anyone does to it, and it takes a true gunsmith to do any real work on it. Uses 7.62x25mm."
ITEM.Model = "models/weapons/w_c96_one_handed.mdl"
ITEM.WeaponClass = "tfa_nam_c96"
ITEM.Weight = 2.65
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0015
ITEM.DegradeRate = 0.024
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1.7, 8, 0 )
ITEM.SelfRepairCondition = 95
ITEM.AmmoType = "762x25"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 175000
ITEM.Slot = 2
ITEM.TertiarySlot = true
ITEM.W = 2
ITEM.H = 1