ITEM.Name = "Fort 500"
ITEM.Desc = "A Ukrainian police shotgun. Rugged and reliable, and inexpensive to maintain thanks to domestic manufacture. Uses 12 gauge. Comes in a box due to missing world model."
ITEM.Model = "models/props_junk/cardboard_box003a.mdl"
ITEM.WeaponClass = "tfa_ins2_fort500"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 12
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 14, 0, 0 )
ITEM.SelfRepairCondition = 60
ITEM.AmmoType = "12ga"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 55000
ITEM.Slot = 2
