ITEM.Name = "AN-94"
ITEM.Desc = "Complex in design, high performance assault rifle originally intended to replace the AK-74. Possesses the unique ability to fire deadly accurate two round bursts. Uses 5.45x39mm."
ITEM.Model = "models/weapons/tfa_ins2/w_abakan.mdl"
ITEM.WeaponClass = "tfa_ins2_abakan"
ITEM.Weight = 3.75
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.012
ITEM.FOV 			= 12;
ITEM.CamPos 		= Vector( 100, 100, 0 );
ITEM.LookAt 		= Vector( 4, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "ammo_545x39"
ITEM.License = "B"
ITEM.BulkPrice = 163500
ITEM.Damage = 34