ITEM.Name = "MAT-49"
ITEM.Desc = "A refined French submachine gun for refined stalkers. Folds up for easy concealment inside of a baguette. Chambered in 9x19mm."
ITEM.Model = "models/weapons/w_mat49.mdl"
ITEM.WeaponClass = "tfa_nam_mat49"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.026
ITEM.FOV 			= 10
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 7, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = "B"
ITEM.BulkPrice = 67000
ITEM.Slot = 2
ITEM.Damage = 33