ITEM.Name = "Colt King Cobra"
ITEM.Desc = "A medium frame double-action revolver marketed to law enforcement agencies and civilian firearms enthusiasts. Chambered in .357 Magnum."
ITEM.Model = "models/weapons/tfa_ins2/w_thanez_cobra.mdl"
ITEM.WeaponClass = "tfa_ins2_thanez_cobra"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 7
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1.75, 8, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_357mag"
ITEM.License = "B"
ITEM.BulkPrice = 162500
ITEM.Slot = 2
ITEM.Damage = 59
ITEM.Rarity = 4