ITEM.Name = "H&K MP7"
ITEM.Desc = "German personal defense weapon utilized in police departments worldwide. For better or worse, the 4.6x30mm it spits is as armor-piercing as it is rare."
ITEM.Model = "models/weapons/tfa_ins2/w_mp7.mdl"
ITEM.WeaponClass = "tfa_ins2_mp7"
ITEM.Weight = 2.5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.015
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 2, 0, -1 )
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "ammo_46x30"
ITEM.BulkPrice = 112500
ITEM.Slot = 2
ITEM.Damage = 28
ITEM.Rarity = 4
ITEM.RepairCost = 9