ITEM.Name = "Mosin-Nagant M91/30"
ITEM.Desc = "Bolt action rifle of old. Not a sniper variant but still has it's massively long barrel. Uses 762x54R."
ITEM.Model = "models/weapons/tfa_ins2/w_mosin.mdl"
ITEM.WeaponClass = "tfa_ins2_mosin"
ITEM.Weight = 5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0003
ITEM.DegradeRate = 0.01
ITEM.FOV 			= 8;
ITEM.CamPos 		= Vector( 100, 100, 25 );
ITEM.LookAt 		= Vector( 7, 0, 1 );
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "762x54r"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 68000
ITEM.Slot = 2
ITEM.SlotPos = 1
