ITEM.Name = "Flare Gun"
ITEM.Desc = "Used to create illumination for improved vision or as a distress signal. Legally blinding."
ITEM.Model = "models/weapons/w_monkflaregun.mdl"
ITEM.WeaponClass = "tfa_mats_flaregun"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 5.5, -1.5, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "flare"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 10000
ITEM.Slot = 2
ITEM.TertiarySlot = true
ITEM.W = 2
ITEM.H = 1