ITEM.Name = "Glock 19"
ITEM.Desc = "A popular handgun for police, military and civilian applications the world around. Versatile and rugged."
ITEM.Model = "models/weapons/tfa_ins2/w_glock19.mdl"
ITEM.WeaponClass = "tfa_ins2_glock_19"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 55000