ITEM.Name = "KA-BAR"
ITEM.Desc = "Service with a smile since 1942. Can be fashioned into a spear using the loop on the crossguard."
ITEM.Model = "models/weapons/tfa_ins2/w_marinebayonet.mdl"
ITEM.WeaponClass = "tfa_ins2_kabar"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.1
ITEM.FOV 			= 16;
ITEM.CamPos 		= Vector( 0, 50, 0 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.W = 2
ITEM.H = 1
ITEM.SelfRepairCondition = 40
ITEM.License = "X"
ITEM.BulkPrice = 15000
ITEM.Slot = 1
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true