ITEM.Name = "S&W 659"
ITEM.Desc = "A chrome (shine not included) pistol for the stalker more concerned with bling. Still a decent pistol but just a pistol.  Uses 9x19."
ITEM.Model = "models/weapons/tfa_ins2/w_sw659.mdl"
ITEM.WeaponClass = "tfa_ins2_sw659"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.05
ITEM.DegradeRate = 0.08
ITEM.FOV 			= 7;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 90
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 75000
