ITEM.Name = "FNP-45"
ITEM.Desc = "A modern handgun manufactured in Columbia, South Carolina, by FNH USA. Debuted in 2006. Popular among mercenaries and gun enthusiasts. Fires .45 ACP."
ITEM.Model = "models/weapons/w_ins2_pist_fnp45.mdl"
ITEM.WeaponClass = "tfa_ins2_fnp45"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0001
ITEM.DegradeRate = 0.0166
ITEM.FOV 			= 6;
ITEM.CamPos 		= Vector( 0, 100, 0 );
ITEM.LookAt 		= Vector( 0.75, 0, 0 );
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "ammo_45acp"
ITEM.License = "B"
ITEM.BulkPrice = 112500
ITEM.Slot = 2
ITEM.SlotPos = 1
ITEM.Damage = 45
ITEM.Rarity = 4
ITEM.RepairCost = 9
ITEM.Vars = {
	Equipped = false,
	CurrentAttachments = {},
	Upgrades = {
		generic_opt_mount = true,
        generic_barrel_thread = true,
        generic_underbarrel_mount = true,
	},
	Durability = 100,
	Clip1 = 0,
}