ITEM.Name = "SIG P220"
ITEM.Desc = "Developed in 1975 by SIG and produced and distributed by J.P. Sauer & Sohn, the SIG P226 has earned a reputation for its excellent ergonomics and accuracy. Uses .45 ACP."
ITEM.Model = "models/weapons/tfa_ins2/w_p220.mdl"
ITEM.WeaponClass = "tfa_ins2_p220"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.032
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25)
ITEM.LookAt 		= Vector( 1, 0, 0 )
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "45acp"
ITEM.License = "B"
ITEM.BulkPrice = 71000
ITEM.Slot = 2
