ITEM.Name = "M4 Spectre"
ITEM.Desc = "A scarce but excellent submachine gun made in Italy. Due to its rarity, it commands a premium on the open market. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/w_spectre.mdl"
ITEM.WeaponClass = "tfa_ins2_spectre"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.00025
ITEM.DegradeRate = 0.018
ITEM.FOV 			= 10;
ITEM.CamPos 		= Vector( 0, 100, 25 );
ITEM.LookAt 		= Vector( 2, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "9x19"
ITEM.License = "C"
ITEM.BulkPrice = 180000
