ITEM.Name = "M3 Grease Gun"
ITEM.Desc = "A sturdy and reliable American submachine gun that's seen service from WW2 all the way until present day. Uses .45 ACP."
ITEM.Model = "models/weapons/w_smg_xoma_x4_m3grease.mdl"
ITEM.WeaponClass = "xoma_x4_m3grease"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0009
ITEM.DegradeRate = 0.016
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 0, 0, -1.5 )
ITEM.SelfRepairCondition = 65
ITEM.AmmoType = "45acp"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 50000
ITEM.Slot = 2
