ITEM.Name = "MR96"
ITEM.Desc = "French-manufactured, high-end double-action/single-action revolver. Chambered in .357."
ITEM.Model = "models/weapons/w_mr96.mdl"
ITEM.WeaponClass = "tfa_ins2_mr96"
ITEM.Weight = 2.25
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 2, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "B"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 100000
ITEM.Slot = 2
