ITEM.Name = "Ultimax 100"
ITEM.Desc = "A lightweight and handy machine gun. Due to its compact size and cool looks, it is occasionally seen with wealthier mercenaries. Uses 5.56x45mm."
ITEM.Model = "models/weapons/private_arsenals/w_ultimax100.mdl"
ITEM.WeaponClass = "tfa_private_ultimax100"
ITEM.Weight = 4.9
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00015
ITEM.DegradeRate = 0.01
ITEM.FOV 			= 12;
ITEM.CamPos 		= Vector( 100, 100, 25 );
ITEM.LookAt 		= Vector( 8, 0, 0 );
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "ammo_556x45mm"
ITEM.License = "C"
ITEM.BulkPrice = 290000
ITEM.Damage = 33
