ITEM.Name = "Uberti 1873 Peacemaker"
ITEM.Desc = "A modern copy of the Colt 1873 Peacemaker revolver. These replicas are un- or lightly-regulated in many European countries, so they often pop up in criminal circles. Chambered in .357 Magnum."
ITEM.Model = "models/weapons/tfre/w_peacemaker.mdl"
ITEM.WeaponClass = "tfa_tfre_colt_peacemaker"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, -100, 25 )
ITEM.LookAt 		= Vector( -0.5, -5, 0 )
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "357mag"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 64000
ITEM.Slot = 2
ITEM.TertiarySlot = true
ITEM.W = 2
ITEM.H = 1