ITEM.Name = "Mk 23"
ITEM.Desc = "Built on a sturdier frame than the USP, the MK23 is an oversized gun for specialists or people who need to break necks when they pistol whip. Prefered by spies and Mercs. Uses .45 ACP."
ITEM.Model = "models/weapons/tfa_ins2/w_mk23.mdl"
ITEM.WeaponClass = "tfa_ins2_mk23"
ITEM.Weight = 1.75
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00021
ITEM.DegradeRate = 0.015
ITEM.FOV 			= 7;
ITEM.CamPos 		= Vector( 0, 100, 25 );
ITEM.LookAt 		= Vector( 1.5, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "ammo_45acp"
ITEM.License = "B"
ITEM.BulkPrice = 182500
ITEM.Damage = 45
ITEM.Rarity = 4
ITEM.RepairCost = 15
ITEM.Vars = {
	Equipped = false,
	CurrentAttachments = {},
	Upgrades = {
		generic_barrel_thread = true,
        generic_underbarrel_mount = true,
	},
	Durability = 100,
	Clip1 = 0,
}