ITEM.Name = "AK-74"
ITEM.Desc = "The 1970s replacement for the AKM, firing an intermediate high velocity round. It achieves greater effective range, accuracy, and reliability than its predecessor. Fires 5.45x39mm."
ITEM.Model = "models/weapons/w_tfa_dm_ak74.mdl"
ITEM.WeaponClass = "tfa_dm_ak74"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00045
ITEM.DegradeRate = 0.012
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 75, 100, 0 )
ITEM.LookAt 		= Vector( 0, 0, 5 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "545x39"
ITEM.License = "A"
ITEM.BulkPrice = 67000
ITEM.Damage = 34