ITEM.Name = "Crowbar"
ITEM.Desc = "Scourge of boxes, mutants, and alien invaders the world around."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_crowbar.mdl"
ITEM.WeaponClass = "tfa_nmrih_crowbar"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 40
ITEM.License = "A"
ITEM.BulkPrice = 7500
ITEM.Slot = 1
