ITEM.Name = "PKP"
ITEM.Desc = "A modernized PKM. Obviously rarer than the PKM. Not many differences aside from a more accurate but non-removable barrel.  Uses 7.62x54R."
ITEM.Model = "models/weapons/tfa_ins2/w_pkm.mdl"
ITEM.WeaponClass = "tfa_ins2_pkp"
ITEM.Weight = 8.75
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.03
ITEM.DegradeRate = 0.010
ITEM.FOV 			= 21;
ITEM.CamPos 		= Vector( 83.93, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "762x54r"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 255000
