ITEM.Name = "Beretta 92"
ITEM.Desc = "In service with various military and law enforcement organizations worldwide, Beretta pistols are equally popular in the criminal underworld. They are usually dated, and come from retired stock. Chambered in 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/w_m9.mdl"
ITEM.WeaponClass = "tfa_ins2_m9"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.0155
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_9x19"
ITEM.License = "A"
ITEM.BulkPrice = 45000
ITEM.Slot = 2
