ITEM.Name = "H&K USP 45"
ITEM.Desc = "An accurate and ultra-reliable polymer pistol chambered in .45 ACP. A bit hefty, though."
ITEM.Model = "models/weapons/tfa_ins2/w_usp45.mdl"
ITEM.WeaponClass = "tfa_ins2_usp45"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0001
ITEM.DegradeRate = 0.021
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "45acp"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 75000
ITEM.Slot = 2
ITEM.TertiarySlot = true