ITEM.Name = "Colt M1911"
ITEM.Desc = "An old-school, .45 ACP, hard hitter. Intimidating and powerful, but sorely outdated and hindered by its small magazine."
ITEM.Model = "models/weapons/tfa_ins2/w_m1911.mdl"
ITEM.WeaponClass = "tfa_ins2_m1911"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0003
ITEM.DegradeRate = 0.04
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_45acp"
ITEM.License = "B"
ITEM.BulkPrice = 54000
ITEM.Slot = 2
ITEM.Damage = 45
ITEM.Rarity = 2
ITEM.RepairCost = 5