ITEM.Name = "SIG P226"
ITEM.Desc = "Developed in 1975 by SIG and produced and distributed by J.P. Sauer & Sohn, the SIG P226 has earned a reputation for its excellent ergonomics and accuracy.  Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/w_p226.mdl"
ITEM.WeaponClass = "tfa_ins2_p226"
ITEM.Weight = 1.25
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.028
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 1, 0, 0 )
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "9x19"
ITEM.License = "B"
ITEM.BulkPrice = 68000
ITEM.Slot = 2
ITEM.Damage = 33