ITEM.Name = "IMI Jericho"
ITEM.Desc = "A military & police sidearm developed in Israel, but found all over the globe. Uses 9x19."
ITEM.Model = "models/weapons/private_arsenals/w_jericho.mdl"
ITEM.WeaponClass = "tfa_private_jericho"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0008
ITEM.DegradeRate = 0.013
ITEM.FOV 			= 6;
ITEM.CamPos 		= Vector( 0, 100, 25 );
ITEM.LookAt 		= Vector( -0.5, 4, 0 );
ITEM.SelfRepairCondition = 90
ITEM.AmmoType = "ammo_9x19"
ITEM.License = "A"
ITEM.BulkPrice = 61000
ITEM.Damage = 33
ITEM.Rarity = 2