ITEM.Name = "Smith & Wesson Safety Hammerless"
ITEM.Desc = "An antiquated pocket revolver that can still be found in criminal circles all over Europe. Unbelievably tiny and chambered in the wimpy .32 Short & Weak."
ITEM.Model = "models/weapons/tfre/w_hammerless.mdl"
ITEM.WeaponClass = "tfa_tfre_hammerless"
ITEM.Weight = 0.5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.00015
ITEM.DegradeRate = 0.025
ITEM.FOV 			= 5
ITEM.CamPos 		= Vector( 0, -100, 0 )
ITEM.LookAt 		= Vector( 0, 0, -2 )
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "ammo_32acp"
ITEM.License = "A"
ITEM.BulkPrice = 12000
ITEM.Slot = 2
