ITEM.Name = "L2A3 Sterling"
ITEM.Desc = "A British submachine gun of the 1950s. Despite its basic, even antiquated design, the hardy Sterling is still in use all over the world. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/w_sterling.mdl"
ITEM.WeaponClass = "tfa_ins2_sterling"
ITEM.Weight = 2.4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.015
ITEM.FOV 			= 9
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 1, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_9x19"
ITEM.License = "A"
ITEM.BulkPrice = 60000
ITEM.Slot = 2
ITEM.Damage = 34