ITEM.Name = "AKM"
ITEM.Desc = "The classic Russian assault rifle. Tried and true, used all across the world. Uses 7.62x39mm"
ITEM.Model = "models/weapons/tfa_ins2/w_akm.mdl"
ITEM.WeaponClass = "tfa_ins2_akm"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.05
ITEM.DegradeRate = 0.010
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "762x39"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 68000
