ITEM.Name = "Mossberg 500"
ITEM.Desc = "Basic Mossberg shotgun that's been cut down. A good friend to a stalker. Uses 12 gauge shells or slugs."
ITEM.Model = "models/weapons/tfa_ins2/w_m500.mdl"
ITEM.WeaponClass = "tfa_ins2_m500"
ITEM.Weight = 2.25
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.07
ITEM.DegradeRate = 0.110
ITEM.FOV 			= 27;
ITEM.CamPos 		= Vector( 12.5, 50, 50 );
ITEM.LookAt 		= Vector( 8.04, 0, 0 );
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "12ga"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 84000
