ITEM.Name = "Steyr M9-A1"
ITEM.Desc = "A devilishly handsome handgun from Austrian manufacturer Steyr. Its very sharp grip angle makes it point very well. Uses 9x19mm."
ITEM.Model = "models/smc/weapons/steyr-m9a1/w_steyr-m9a1.mdl"
ITEM.WeaponClass = "tfa_smc_m9a1"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.012
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 10, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = "B"
ITEM.BulkPrice = 72000
ITEM.Slot = 2
ITEM.TertiarySlot = true
ITEM.W = 2
ITEM.H = 1
