ITEM.Name = "OTs-14 Groza"
ITEM.Desc = "A bullpup assault rifle used by Russian internal troops. Uses 9x39mm subsonic ammunition."
ITEM.Model = "models/weapons/tfa_ins2/w_groza.mdl"
ITEM.WeaponClass = "tfa_ins2_groza"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.027
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "ammo_9x39"
ITEM.License = "C"
ITEM.BulkPrice = 270000
ITEM.Damage = 36