ITEM.Name = "OTs-03 SVU"
ITEM.Desc = "Bullpup SVD typically used by special police units and other urban specialists. Relatively light and portable. Fires 7.62x54R."
ITEM.Model = "models/weapons/tfa_ins2/w_svu.mdl"
ITEM.WeaponClass = "tfa_ins2_svu"
ITEM.Weight = 3.75
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.015
ITEM.FOV 			= 10;
ITEM.CamPos 		= Vector( 100, 100, 25 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "762x54r"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 220000
