ITEM.Name = "Lead Pipe"
ITEM.Desc = "An improvised club. Cheap and effective; a popular sidearm for rookies."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_pipe_lead.mdl"
ITEM.WeaponClass = "tfa_nmrih_lpipe"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.10
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 100
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 1000
ITEM.Slot = 1
ITEM.W = 1
ITEM.H = 3