ITEM.Name = "Barrett M82"
ITEM.Desc = "An enormous and cumbersome sniper rifle which promises ultimate dick-waving cred. Optics included. Uses .50 BMG."
ITEM.Model = "models/weapons/private_arsenals/w_m82.mdl"
ITEM.WeaponClass = "tfa_private_m82"
ITEM.Weight = 20
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 15, 0, 3 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_50bmg"
ITEM.License = "C"
ITEM.BulkPrice = 937500
ITEM.Slot = 2
ITEM.NoDefaultAtts = true
ITEM.Damage = 150