ITEM.Name = "Kimber Night Warrior"
ITEM.Desc = "A 1911 for the stalker or Merc wanting a bit more accuracy and modernity. Not a gun to be left unmaintained.  Uses .45 ACP."
ITEM.Model = "models/weapons/w_nb_ins_knw.mdl"
ITEM.WeaponClass = "tfa_ins2_knw"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.01
ITEM.DegradeRate = 0.04
ITEM.FOV 			= 10;
ITEM.CamPos 		= Vector( 50, 50, 50 );
ITEM.LookAt 		= Vector( 0, 0, 0 );
ITEM.SelfRepairCondition = 90
ITEM.AmmoType = "45acp"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 105000
