ITEM.Name = "FN MAG"
ITEM.Desc = "A Belgian mediumm machine gun lauded for its reliability and versatility. Uses 7.62x51mm rounds."
ITEM.Model = "models/weapons/private_arsenals/w_m240g.mdl"
ITEM.WeaponClass = "tfa_private_m240g"
ITEM.Weight = 11
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00045
ITEM.DegradeRate = 0.0091
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 10, -2, 2 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_762x51"
ITEM.License = "B"
ITEM.BulkPrice = 420000
ITEM.Slot = 2
ITEM.Damage = 51
ITEM.Rarity = 4
ITEM.RepairCost = 34
ITEM.Vars = {
	Equipped = false,
	CurrentAttachments = {},
	Upgrades = {
		generic_opt_mount = true,
	},
	Durability = 100,
	Clip1 = 0,
}