ITEM.Name = "GSh-18"
ITEM.Desc = "A Russian pistol designed to handle extreme overpressure rounds. Mechanically complex, this pistol requires more maintenance than normal to remain reliable. Uses 9x19mm."
ITEM.Model = "models/weapons/w_gsh18.mdl"
ITEM.WeaponClass = "tfa_ins2_gsh18"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0008
ITEM.DegradeRate = 0.025
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( 0, 0, 0 )
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "ammo_9x19"
ITEM.License = "B"
ITEM.BulkPrice = 77000
ITEM.Slot = 2
ITEM.Damage = 33
ITEM.Rarity = 3