ITEM.Name = "P2008"
ITEM.Desc = "A modernized replica of the classic Luger pistol, built for discerning clients on an individual basis by a specialist gunsmith in Germany. Expensive far beyond practicality."
ITEM.Model = "models/weapons/tfa_cod/mwr/w_br9.mdl"
ITEM.WeaponClass = "tfa_mwr_br9"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.02
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 200000
ITEM.Slot = 2