ITEM.Name = "Colt 1903 Pocket Hammerless"
ITEM.Desc = "A sleek and well-made early semi-automatic design that stood the test of time, remaining in many military inventories through the better part of the 20th century. Chambered for .32 ACP."
ITEM.Model = "models/weapons/w_ww1_mle1903.mdl"
ITEM.WeaponClass = "tfa_ww1_mle1903"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00015
ITEM.DegradeRate = 0.025
ITEM.FOV 			= 5
ITEM.CamPos 		= Vector( 0, -100, 0 )
ITEM.LookAt 		= Vector( 0, 0, -2 )
ITEM.SelfRepairCondition = 75
ITEM.AmmoType = "ammo_32acp"
ITEM.License = "B"
ITEM.BulkPrice = 12000
ITEM.Slot = 2
ITEM.Damage = 28