ITEM.Name = "Stihl Abrasive Saw"
ITEM.Desc = "A gas-powered chop saw with a gnarly blade capable of cutting through concrete and steel. And other things."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_abrasivesaw.mdl"
ITEM.WeaponClass = "tfa_nmrih_asaw"
ITEM.Weight = 10
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.05
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 150000
ITEM.Slot = 1
ITEM.AmmoType = "gas"
ITEM.W = 2
ITEM.H = 2