ITEM.Name = "RPG-7"
ITEM.Desc = "This rocket-propelled grenade launcher needs no introduction."
ITEM.Model = "models/weapons/tfa_ins2/w_rpg.mdl"
ITEM.WeaponClass = "tfa_ins2_rpg"
ITEM.Weight = 9
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.5
ITEM.FOV 			= 10
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( -5, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_rpg"
ITEM.License = "B"
ITEM.BulkPrice = 350000
ITEM.Slot = 2
ITEM.Rarity = 3
ITEM.RepairCost = 14