ITEM.Name = "Hatchet"
ITEM.Desc = "A handy camping tool, popular with woodsmen."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_hatchet.mdl"
ITEM.WeaponClass = "tfa_nmrih_hatchet"
ITEM.Weight = 2
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 40
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 10000