ITEM.Name = "Sledgehammer"
ITEM.Desc = "A demolition tool that doesn't know the difference between drywall and bone."
ITEM.Model = "models/weapons/tfa_nmrih/w_me_sledge.mdl"
ITEM.WeaponClass = "tfa_nmrih_sledge"
ITEM.Weight = 6
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0
ITEM.DegradeRate = 0.01
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 50
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 10000
ITEM.Slot = 1