ITEM.Name = "IMI Uzi"
ITEM.Desc = "The Israeli submachine gun that redefined submachine guns. Okay, that's a bit of a stretch. But it is pretty cool. Chambered in 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/w_uzi.mdl"
ITEM.WeaponClass = "tfa_ins2_uzi"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.026
ITEM.FOV 			= 10
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 7, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_9x19"
ITEM.License = "B"
ITEM.BulkPrice = 82500
ITEM.Slot = 2
ITEM.Damage = 34
ITEM.Rarity = 3