ITEM.Name = "TOZ-194m"
ITEM.Desc = "A combat shotgun designed around the legal limits of civilian ownership in Russia. Uses 12-gauge."
ITEM.Model = "models/weapons/w_inss2_toz_194m.mdl"
ITEM.WeaponClass = "tfa_ins2_toz_194m"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.032
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 10, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "B"
ITEM.BulkPrice = 30000
ITEM.Slot = 2
ITEM.Damage = 10
ITEM.Rarity = 2