ITEM.Name = "Karabiner 98k"
ITEM.Desc = "A bolt-action rifle dating back almost a hundred years. Accurate, and packs a punch. Uses 8mm Mauser."
ITEM.Model = "models/weapons/tfa_ins2/w_k98.mdl"
ITEM.WeaponClass = "tfa_ins2_k98"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.012
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 12, 0, 0 )
ITEM.SelfRepairCondition = 60
ITEM.AmmoType = "ammo_792x57"
ITEM.License = "B"
ITEM.BulkPrice = 82500
ITEM.Slot = 2
ITEM.Damage = 80