ITEM.Name = "SPAS 12"
ITEM.Desc = "A heavy police shotgun with the ability to fire in semi-auto or pump action.  Picky with it's ammo.  Has a cool folding stock but the gun itself is heavy and not optimal.  Uses 12 gauge."
ITEM.Model = "models/weapons/tfa_ins2/w_spas12_bri.mdl"
ITEM.WeaponClass = "tfa_ins2_spas12"
ITEM.Weight = 4.5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0009
ITEM.DegradeRate = 0.015
ITEM.FOV 			= 10;
ITEM.CamPos 		= Vector( 100, 100, 25 );
ITEM.LookAt 		= Vector( 12.5, 0, 0 );
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "C"
ITEM.BulkPrice = 150000
