ITEM.Name = "Mossberg M590"
ITEM.Desc = "A widely distributed tactical shotgun popular with police and military forces all over the globe as well as civilian shooters. Fires 12 gauge."
ITEM.Model = "models/weapons/tfa_ins2/w_m590.mdl"
ITEM.WeaponClass = "tfa_ins2_m590"
ITEM.Weight = 2.65
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.00045
ITEM.DegradeRate = 0.011
ITEM.FOV 			= 46
ITEM.CamPos 		= Vector( 50, 4.47, 0.9 )
ITEM.LookAt 		= Vector( -90, -4.82, 4.83 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "B"
ITEM.BulkPrice = 82000
ITEM.Slot = 2
