ITEM.Name = "Browning Auto-5"
ITEM.Desc = "An older semi-automatic shotgun. Powerful, but finicky. Uses 12 gauge."
ITEM.Model = "models/weapons/w_ins2_auto5.mdl"
ITEM.WeaponClass = "tfa_ww1_auto5"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.0143
ITEM.FOV 			= 9
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 7, 0, 0 )
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "B"
ITEM.BulkPrice = 60000
ITEM.Slot = 2
ITEM.Damage = 13
ITEM.Rarity = 3