ITEM.Name = "MP-443 Grach"
ITEM.Desc = "A newer Russian service pistol. Hard to find, but a handy sidearm. Uses 9x19mm."
ITEM.Model = "models/weapons/tfa_ins2/mp443/w_mp443.mdl"
ITEM.WeaponClass = "tfa_ins2_mp443"
ITEM.Weight = 1
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0005
ITEM.DegradeRate = 0.03
ITEM.FOV 			= 6;
ITEM.CamPos 		= Vector( 0, 100, 25 );
ITEM.LookAt 		= Vector( 1, 0, 0 );
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "9x19"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 65000
ITEM.TertiarySlot = true
ITEM.W = 2
ITEM.H = 1