ITEM.Name = "FN Minimi"
ITEM.Desc = "A belt-fed light machine gun developed in Belgium. 5.56x45mm."
ITEM.Model = "models/weapons/smc/minimi/w_minimi.mdl"
ITEM.WeaponClass = "tfa_smc_minimi"
ITEM.Weight = 6
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00045
ITEM.DegradeRate = 0.0091
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 10, -2, 2 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_556x45"
ITEM.License = "C"
ITEM.BulkPrice = 385000
ITEM.Slot = 2
ITEM.Damage = 33