ITEM.Name = "Stevens Model 620"
ITEM.Desc = "The Stevens M620 was an improved version of John Moses Browning's earlier M520 series, primarily with a more refined receiver. Uses 12-gauge."
ITEM.Model = "models/weapons/w_nam_stevens620.mdl"
ITEM.WeaponClass = "tfa_nam_stevens620"
ITEM.Weight = 6
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.016
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 10, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "B"
ITEM.BulkPrice = 50000
ITEM.Slot = 2
