ITEM.Name = "FN Five-seveN"
ITEM.Desc = "A 5.7x28mm handgun produced in Belgium. Large magazine size and armor-piercing capability. Uses 5.7x28mm."
ITEM.Model = "models/weapons/tfa_ins2/w_fn57.mdl"
ITEM.WeaponClass = "tfa_ins2_fiveseven"
ITEM.Weight = 1.5
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00025
ITEM.DegradeRate = 0.03
ITEM.FOV 			= 6
ITEM.CamPos 		= Vector( 0, 100, 25 )
ITEM.LookAt 		= Vector( -1, 0, 0 )
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "ammo_57x28"
ITEM.License = "B"
ITEM.BulkPrice = 117500
ITEM.Slot = 2
ITEM.Damage = 29
ITEM.Rarity = 4