ITEM.Name = "Benelli M1014"
ITEM.Desc = "A 12 gauge Italian semi-automatic shotgun designed for tactical applications. A sureshot under the harshest conditions."
ITEM.Model = "models/weapons/tfa_ins2/w_m1014.mdl"
ITEM.WeaponClass = "tfa_ins2_m1014"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.005
ITEM.DegradeRate = 0.02
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 7, 0, 0 )
ITEM.SelfRepairCondition = 80
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "B"
ITEM.BulkPrice = 165000
ITEM.Slot = 2
ITEM.Rarity = 4