ITEM.Name = "MTs-255"
ITEM.Desc = "A five-shot revolving shotgun, presumably developed for hunting bigfoot. Uses 12 gauge."
ITEM.Model = "models/weapons/tfa_ins2/w_mc255.mdl"
ITEM.WeaponClass = "tfa_ins2_mc255"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.0008
ITEM.DegradeRate = 0.04
ITEM.Damage = 10
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 15, 0, 0 )
ITEM.SelfRepairCondition = 85
ITEM.AmmoType = "ammo_12ga"
ITEM.License = "B"
ITEM.BulkPrice = 60000
ITEM.Slot = 2
ITEM.Rarity = 3
ITEM.RepairCost = 7
ITEM.Vars = {
	Equipped = false,
	CurrentAttachments = {},
	Upgrades = {
		generic_opt_mount = true,
	},
	Durability = 100,
	Clip1 = 0,
},