ITEM.Name = "IMI Uzi"
ITEM.Desc = "The Israeli submachine gun that redefined submachine guns. Okay, that's a bit of a stretch. But it is pretty cool."
ITEM.Model = "models/weapons/tfa_ins2/w_uzi.mdl"
ITEM.WeaponClass = "tfa_ins2_uzi"
ITEM.Weight = 3
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.026
ITEM.FOV 			= 10
ITEM.CamPos 		= Vector( 100, 100, 25 )
ITEM.LookAt 		= Vector( 7, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "9x19"
ITEM.License = "B"
ITEM.BulkPrice = 75000
ITEM.Slot = 2
