ITEM.Name = "Bren machine gun"
ITEM.Desc = "Although awkward looking, the battle-proven Bren is a well-balanced and easy to operate machine gun. Converted to 7.62x51mm after the war."
ITEM.Model = "models/weapons/tfa_doi/w_bren.mdl"
ITEM.WeaponClass = "tfa_doibren"
ITEM.Weight = 12
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Vector(-12.4, 0, 0)
ITEM.JamChance = 0.00045
ITEM.DegradeRate = 0.0091
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 10, -2, 2 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "ammo_762x51"
ITEM.BulkPrice = 385000
ITEM.Slot = 2
ITEM.Damage = 51
ITEM.Rarity = 4
ITEM.RepairCost = 30
