ITEM.Name =  "Adhesive";
ITEM.Desc =  "A bottle of glue to stick things together.";
ITEM.Model =  "models/props_junk/garbage_plasticbottle001a.mdl";
ITEM.Weight =  0.33;
ITEM.FOV =  14;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  50;
ITEM.License =  "X"
ITEM.ConsumeText = "After a moment of struggle, you force the childproof lid off and dribble the liquid glue into your mouth. Are you okay?"
ITEM.UseText = "Drink"
ITEM.HungerReduce = -10
