ITEM.Name =  "Altoids (Peppermint)"
ITEM.Desc =  "An imported tin of a popular Western treat. These ones are peppermint flavored, and quite refreshing."
ITEM.Model =  "models/kek1ch/dev_mint.mdl"
ITEM.Weight =  0.1
ITEM.FOV = 20
ITEM.CamPos = Vector( 50, 50, 50 )
ITEM.LookAt = Vector( 0, 0, 0 )
ITEM.PhysicalMass    = 1
ITEM.BulkPrice =  40
ITEM.License =  "F"
ITEM.ConsumeText = "You pop open the lid and toss some of the tablets in your mouth. You salivate as they melt, your thirst for water artificially quenched just a little bit."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 4
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true