ITEM.Name =  "Beans";
ITEM.Desc =  "A dinged-up can of baked beans. It's still perfectly sealed.";
ITEM.Model =  "models/kek1ch/dev_beans.mdl";
ITEM.Weight =  0.5;
ITEM.FOV =  7;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  250;
ITEM.License =  "X"
ITEM.ConsumeText = "You pull the tab on the can of uncooked beans and eat them. Soft, sweet, and only a slight aftertaste of aluminum."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 25
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true