ITEM.Name =  "Beans";
ITEM.Desc =  "A can of beans.";
ITEM.Model =  "models/props_junk/garbage_metalcan001a.mdl";
ITEM.Weight =  1;
ITEM.FOV =  7;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  25;
ITEM.License =  LICENSE_FOOD;
ITEM.ConsumeText = "You open and eat the can of uncooked beans."
ITEM.UseText = "Eat"