ITEM.Name =  "Beer"
ITEM.Desc =  "A bottle of skunky Czech beer."
ITEM.Model =  "models/kek1ch/dev_beer.mdl"
ITEM.Weight =  0.33
ITEM.FOV =  11
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice =  500
ITEM.License =  "F"
ITEM.ConsumeText = "You pop the cap with your teeth and drink the beer. It's not great, but it scratches the itch."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 15
ITEM.RadiationHealAmount = 5
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true