ITEM.Name =  "Beer";
ITEM.Desc =  "A bottle of skunky Czech beer.";
ITEM.Model =  "models/props_junk/garbage_glassbottle003a.mdl";
ITEM.Weight =  1;
ITEM.FOV =  11;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  50;
ITEM.License =  LICENSE_ALCOHOL;
ITEM.ConsumeText = "You pop the cap and drink the beer."
ITEM.UseText = "Drink"