ITEM.Name =  "Boar chop";
ITEM.Desc =  "A hearty hunk of fatty meat cut from the carcass of a boar. Slightly irradiated, but not especially dangerous to consume, other than the worms.";
ITEM.Model =  "models/gibs/humans/mgib_01.mdl";
ITEM.Weight =  2;
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.ConsumeText = "You take a big, hungry bite out of the hunk of meat. It's chewy and hard to get down, but it's packed with deliciously meaty protein and fills you up nicely."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 65