ITEM.Name =  "Booster Energy Drink";
ITEM.Desc =  "A dangerous concoction of uppers and downers in a square plastic bottle. The label's hand-drawn. It smells distinctly of cherry cough syrup.";
ITEM.Model =  "models/stalker/item/medical/booster.mdl";
ITEM.Weight =  2.5;
ITEM.FOV =  7;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.PhysicalMass	= 1;
ITEM.BulkPrice =  500;
ITEM.License =  "X";
ITEM.ConsumeText = "You take a cautious sip from the bottle despite your best instincts. After a few swigs from the odd concoction, you feel an odd sense of serenity with the Zone. Your senses are dulled but you're full of energy."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 50