ITEM.Name =  "Bread";
ITEM.Desc =  "Half of a loaf of rye bread. Pairs great with canned meat and pats of butter.";
ITEM.Model =  "models/kek1ch/dev_bred.mdl";
ITEM.Weight =  0.33;
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  200;
ITEM.License =  "X";
ITEM.ConsumeText = "Your teeth can just barely penetrate the rockhard crust of the bread. It was well worth it. You feel nourished to an extent."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 20
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true