ITEM.Name =  "Fresh Bread"
ITEM.Desc =  "Crunchy on the outside, soft on the inside. Presumably Zone-made in the past few days."
ITEM.Model =  "models/kali/miscstuff/stalker/food/bread.mdl"
ITEM.Weight =  0.25
ITEM.FOV =  12
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice =  500
ITEM.License =  "F"
ITEM.ConsumeText = "Your mouth confirms with joy that this is, indeed, good ass bread; pleasantly ordinary, and thankfully far from stale."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 50
ITEM.Rarity = 3
ITEM.AllowRandomSpawn = true