ITEM.Name =  "Brick";
ITEM.Desc =  "The budget boot knife. A tried and true solution to conflict since the time of the caveman.";
ITEM.Model =  "models/z-o-m-b-i-e/st/vehicles/cars/st_polevaya_kuhnya_01_6.mdl";
ITEM.Weight =  1;
ITEM.FOV =  20;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  100
ITEM.W = 2
ITEM.H = 1
ITEM.ConsumeText = "You crack off a corner of the brick and eat it. Crunchy and not satisfying at all. You chipped your tooth doing that, too. What were you thinking?"
ITEM.UseText = "Eat"
ITEM.Rarity = 1
ITEM.AllowRandomSpawn = true