ITEM.Name =  "Burnt Beans";
ITEM.Desc =  "A barely recognizable can of beans that probably went for a rumble in a Burner.";
ITEM.Model =  "models/props_junk/garbage_metalcan001a.mdl";
ITEM.Weight =  0.1;
ITEM.FOV =  7;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice = 5
ITEM.ConsumeText = "You pick off the crusty, scorched lid of the can and scrape out the burnt remnants. Despite how peckish you are, you don't think you can stomach even a bite. You'll go hungry instead."
ITEM.UseText = "Eat"
ITEM.Rarity = 1
ITEM.AllowRandomSpawn = true