ITEM.Name =  "Clean Water";
ITEM.Desc =  "A bottle of water, purified and boiled before being sealed.";
ITEM.Model =  "models/kek1ch/dev_mineral_water.mdl";
ITEM.Weight =  .5;
ITEM.FOV =  7;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0.18 );
ITEM.BulkPrice =  200;
ITEM.License =  "X";
ITEM.ConsumeText = "You open and drink the entire bottle. Like a breath of fresh air, it refreshes you."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 20
ITEM.Rarity = 3
ITEM.AllowRandomSpawn = true