ITEM.Name =  "Coffee Beans";
ITEM.Desc =  "A box of coffee beans - rare to find these days. Boil some water and add these.";
ITEM.Model =  "models/kek1ch/dev_caffeine.mdl";
ITEM.Weight =  0.5;
ITEM.FOV =  9;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, -1.26 );
ITEM.BulkPrice =  5;
ITEM.License =  "X"
ITEM.W = 1
ITEM.H = 2
ITEM.ConsumeText = "You take a couple coffee beans and pop them in your mouth. The strong coffee flavor lingers in your mouth as you chew. An unconventional snack, these would be great with some chocolate."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 1
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true