ITEM.Name =  "Cooked Beans"
ITEM.Desc =  "A can of hot cooked beans. A British delicacy served over toast."
ITEM.Model =  "models/kek1ch/dev_chili.mdl"
ITEM.Weight =  0.33
ITEM.FOV =  7
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice = 375
ITEM.License = "F"
ITEM.ConsumeText = "You open and tip the can of cooked beans into your mouth. Ouch. They burn your mouth, but it's worth it for how damn good they are. Hot food will always be a luxury."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 37
ITEM.Rarity = 3
ITEM.AllowRandomSpawn = true