ITEM.Name =  "Cossacks Vodka";
ITEM.Desc =  "A clear liquor distilled by the Katkov company. 65% alcohol, by volume.";
ITEM.Model =  "models/kali/miscstuff/stalker/food/cossacks vodka.mdl";
ITEM.Weight =  1;
ITEM.FOV =  7;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  1250;
ITEM.License =  "X";
ITEM.ConsumeText = "You have a hearty swig of vodka. It feels right."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 25
ITEM.RadiationHealAmount = 10