ITEM.Name =  "Cossacks Vodka"
ITEM.Desc =  "A clear liquor distilled by the Katkov company. 65% alcohol, by volume."
ITEM.Model =  "models/kali/miscstuff/stalker/food/cossacks vodka.mdl"
ITEM.Weight =  0.75
ITEM.FOV =  7
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice =  1250
ITEM.License =  "F"
ITEM.ConsumeText = "You twist and flick off the cap of vodka and have a hearty swig. It feels right."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 20
ITEM.RadiationHealAmount = 10
ITEM.DrugType = "VODKA"
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true