ITEM.Name =  "Box of Crayons"
ITEM.Desc =  "A box of assorted crayons. They double as candles, conveniently."
ITEM.Model =  "models/kek1ch/toolkit_p.mdl"
ITEM.Weight =  0.1
ITEM.FOV =  10;
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice = 5
ITEM.License = "X"
ITEM.ConsumeText = "You crunch down the crayons with ease. Whether you snack one at a time or all at once, these colorful treats are not so easy to get out as they were to get in."
ITEM.UseText = "Eat"
ITEM.HungerReduce = -5
ITEM.Rarity = 1
ITEM.AllowRandomSpawn = true