ITEM.Name =  "Fleshmeat";
ITEM.Desc =  "A hearty hunk of fatty meat cut from the carcass of a flesh. Slightly irradiated, but not especially dangerous to consume, other than the worms.";
ITEM.Model =  "models/kek1ch/meat_boar.mdl";
ITEM.Weight =  .8;
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.ConsumeText = "You take a big, hungry bite out of the hunk of meat. It's chewy and hard to get down, but it's packed with deliciously meaty protein and fills you up nicely."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 45
ITEM.Rarity = 2
ITEM.Experience = 50
ITEM.AllowRandomSpawn = false