ITEM.Name =  "Homemade Halva"
ITEM.Desc =  "The crumbly working mans' treat, made from semechki and sugar."
ITEM.Model =  "models/kali/miscstuff/stalker/food/tourist's breakfast.mdl"
ITEM.Weight =  0.33
ITEM.FOV =  12
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice =  300
ITEM.License =  "F"
ITEM.ConsumeText = "The sweet confection crumbles and crunches in your mouth. It's not much for a meal, but it's a fine dessert."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 30
ITEM.Rarity = 3
ITEM.AllowRandomSpawn = true