ITEM.Name =  "Halva"
ITEM.Desc =  "The crumbly working mans' treat, made from semechki and sugar."
ITEM.Model =  "models/kali/miscstuff/stalker/food/tourist's breakfast.mdl"
ITEM.Weight =  0.33
ITEM.FOV =  12
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice =  150
ITEM.License =  "F"
ITEM.ConsumeText = "The confection crumbles and crunches in your mouth. It's like being at the beach and gnawing on the sand, only it's in oily and rocky clumps. It's not much for a meal, and it's beyond sub-par for a dessert."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 15
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true