ITEM.Name =  "Peach Kompot";
ITEM.Desc =  "A sweet fruity drink, served hot or cold depending on the season. This kompot is made with apples and peaches. The saturated slices of fruit float at the top.";
ITEM.Model =  "models/kali/miscstuff/stalker/food/energy drink.mdl";
ITEM.Weight =  0.5;
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  850;
ITEM.License =  LICENSE_BLACK;
ITEM.ConsumeText = "The sweet liquid washes down your throat, and it's quite satisfying. The solid fruit itself is delightful as well. You remind yourself that such a happily refreshing culinary experience is rare and regret not adequately savoring this one. If only the summer fruits were warmer."
ITEM.UseText = "Drink"