ITEM.Name =  "Kompot";
ITEM.Desc =  "A sweet fruity drink, served hot or cold depending on the season. This kompot is made with... well, something, that's presumably fruit. The indistinct chunks float at the surface of the liquid.";
ITEM.Model =  "models/kali/miscstuff/stalker/food/energy drink.mdl";
ITEM.Weight =  0.25;
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  250;
ITEM.License =  "X";
ITEM.ConsumeText = "The drink goes down like a thin syrup, tasting like a bad mix of artificial sweeteners and preservative. The taste lingers a while after you've gulped down your fill, and only sours the more your smack your lips to try and get it away."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 25
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true