ITEM.Name =  "Homemade Kvass";
ITEM.Desc =  "Homemade bread-beer, from raisins and black bread. The contents are a thick and appetizing dark orange.";
ITEM.Model =  "models/kali/miscstuff/stalker/food/cossacks vodka.mdl";
ITEM.Weight =  0.33;
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  750;
ITEM.License =  "X";
ITEM.ConsumeText = "Taking a drink, you're reminded of nasty western light beers and apple cider. There's not enough alcohol in the kvass for it to be classified as an alcoholic beverage in Russia, but you're certain enough of this stuff will give you a good buzz. It's not a drink for everyone, but it's an enticingly familiar taste."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 20
ITEM.Rarity = 3
ITEM.AllowRandomSpawn = true