ITEM.Name =  "Melon"
ITEM.Desc =  "A fruit, watery and juicy. They grow in squares in Japan!"
ITEM.Model =  "models/props_junk/watermelon01.mdl"
ITEM.Weight =  5
ITEM.FOV =  14
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice =  5000
ITEM.License =  "F"
ITEM.ConsumeText = "You eat the whole fucking melon. Rind and all. You must have been hungry."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 80
ITEM.Rarity = 4
ITEM.AllowRandomSpawn = true