ITEM.Name =  "Milk Carton";
ITEM.Desc =  "A carton of old, spoiled milk. Probably bad for you.";
ITEM.Model =  "models/props_junk/garbage_milkcarton002a.mdl";
ITEM.Weight =  1;
ITEM.FOV =  12;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  5
ITEM.License =  "X"
ITEM.ConsumeText = "You drink the carton of rancid, chunky milk. You consider it lucky that you didn't throw it up immediately."
ITEM.UseText = "Drink"
ITEM.HungerReduce = -5
ITEM.Rarity = 1
ITEM.AllowRandomSpawn = true