ITEM.Name =  "Russian Playboy";
ITEM.Desc =  "25 pages worth of prime nude Russian gals. Probably the best way to travel to a better place, at least mentally.";
ITEM.Model =  "models/kek1ch/porn.mdl";
ITEM.Weight =  0.1;
ITEM.FOV =  13;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  100
ITEM.License =  "X";
ITEM.ConsumeText = "You hungrily oogle the magazine. So many thoughts and fantasies run through your mind, filling you with a primal sense of hunger... Page by page, you cram the magazine into your mouth, chew and swallow. Gulp. Salty."
ITEM.UseText = "Use"
ITEM.HungerReduce = -5
ITEM.RadiationHealAmount = -1
ITEM.Rarity = 1
ITEM.AllowRandomSpawn = true