ITEM.Name =  "Russian IRP-2 Combat Ration"
ITEM.Desc =  "An imported 24hr combat ration issued by the Russian Federation. Essentially, it is a tray of smaller meal components with breakfast, lunch, and dinner compartments. Contains a disposable cooking appliance inside. This menu includes self contained utensils and helpings of biscuits, stewed beef (tushonka), pearl barley and beef (kasha), pork sausage, and buckwheat with more beef. Additionally, there is coffee as well as tea, caramel sweets and apple jam. "
ITEM.Model =  "models/kek1ch/ration_ru.mdl"
ITEM.Weight =  0.33
ITEM.FOV = 20
ITEM.CamPos = Vector( 50, 50, 50 )
ITEM.LookAt = Vector( 0, 0, 0 )
ITEM.PhysicalMass    = 1
ITEM.BulkPrice =  345
ITEM.License =  "X"
ITEM.ConsumeText = "You enjoy one of the ration's individual meal portions."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 20