ITEM.Name =  "Ukrainian Combat Ration"
ITEM.Desc =  "A 24hr combat ration issued by the Ukrainian government. Essentially, it is a tray of smaller meal components with breakfast, lunch, and dinner compartments. The menu mentions helpings of biscuits, pearl barley, beef, liver pate, and honey to enjoy with self contained cutlery. Additionally, there is coffee as well as tea."
ITEM.Model =  "models/kek1ch/ration_ukr.mdl"
ITEM.Weight =  0.33
ITEM.FOV = 20
ITEM.CamPos = Vector( 50, 50, 50 )
ITEM.LookAt = Vector( 0, 0, 0 )
ITEM.PhysicalMass = 1
ITEM.BulkPrice =  310
ITEM.License =  "X"
ITEM.ConsumeText = "You enjoy one of the ration's individual meal portions." 
ITEM.UseText = "Eat"
ITEM.HungerReduce = 20
ITEM.Rarity = 3
ITEM.AllowRandomSpawn = true