ITEM.Name =  "Solyanka"
ITEM.Desc =  "A stew of pitiful leftovers. You can't tell exactly what's in it, just that there's a lot of indistinct... stuff. Hopefully some of it is meat, and all of it is edible."
ITEM.Model =  "models/z-o-m-b-i-e/st/kitchen/st_posuda_konservy_01_3.mdl"
ITEM.Weight =  0.5
ITEM.FOV =  12
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice =  375
ITEM.License =  "F"
ITEM.ConsumeText = "You choke down the cold soup with bitterness. The different chunks of meal remind you of about every different dinner you've experienced over the past month, but all in exceptionally shitty ways. They say hot solyanka is a cure for any sickness, but the way your stomach's beginning to rumble, you wonder if cold solyanka has the opposite effect."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 37
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true