ITEM.Name =  "Tea"
ITEM.Desc =  "A thermos of green tea, made with loose tea leaves and water."
ITEM.Model =  "models/props_junk/garbage_coffeemug001a.mdl"
ITEM.Weight =  0.1
ITEM.FOV =  6
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice = 5
ITEM.License = "F"
ITEM.ConsumeText = "You drink the cold tea. It soothes your throat. This would be great with honey and lemon, you absent-mindedly think."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 1
ITEM.Rarity = 1
ITEM.AllowRandomSpawn = true