ITEM.Name =  "Tourist's Delight"
ITEM.Desc =  "Tinned ham. The kind of cheap stuff Stalkers grab at a gas station just before slipping into the Cordon."
ITEM.Model =  "models/kali/miscstuff/stalker/food/tourist's breakfast.mdl"
ITEM.Weight =  0.25
ITEM.FOV =  8
ITEM.CamPos =  Vector( 50, 50, 50 )
ITEM.LookAt =  Vector( 0, 0, 0 )
ITEM.BulkPrice =  375
ITEM.License =  "F"
ITEM.ConsumeText = "Although overly salty, the knockoff Spam is quite filling. The meat is wet, but it feels dry. The oily aftertaste lingers in your mouth."
ITEM.UseText = "Eat"
ITEM.HungerReduce = 37
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true