ITEM.Name =  "Canned Water";
ITEM.Desc =  "Purified water in a can.";
ITEM.Model =  "models/props_junk/PopCan01a.mdl";
ITEM.Weight =  0.1;
ITEM.FOV =  7;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0.18 );
ITEM.BulkPrice =  175;
ITEM.License =  "X"; 
ITEM.ConsumeText = "You open and drink the entire can. The aftertaste of aluminum lingers in your mouth, but at least you're a little less parched."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 18
ITEM.Rarity = 2
ITEM.AllowRandomSpawn = true