ITEM.Name =  "Red Red Wine";
ITEM.Desc =  "It's up to you.";
ITEM.Model =  "models/props_junk/garbage_glassbottle003a.mdl";
ITEM.Weight =  1.0;
ITEM.FOV =  11;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  1750;
ITEM.License =  "X";
ITEM.ConsumeText = "The red red wine makes you feel so fine."
ITEM.UseText = "Drink"
ITEM.HungerReduce = 25
ITEM.RadiationHealAmount = 5
ITEM.DrugType = "VODKA"