ITEM.Name =  "Advanced Sewing Kit";
ITEM.Desc =  "An unopened, plastic-sealed box of imported sewing supplies, used by the finest quilt-knitting babushkas and professional seamsters alike.";
ITEM.Model =  "models/kek1ch/sewing_kit_a.mdl";
ITEM.Weight =  1.5
ITEM.License = "T"
ITEM.FOV =  10;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 2, -2, 0 );
ITEM.BulkPrice =  20000;
ITEM.License =  "T";
ITEM.SuitOnly = true
ITEM.TechOnly = true
ITEM.RaiseCondition = 40
ITEM.W = 1
ITEM.H = 1