ITEM.Name =  "Basic Sewing Kit";
ITEM.Desc =  "A picked-through collection of sewing supplies. It's not great, but works for a quick patch-up job.";
ITEM.Model =  "models/kek1ch/sewing_kit_b.mdl";
ITEM.Weight =  0.5
ITEM.License = "T"
ITEM.FOV =  10;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 2, -2, 0 );
ITEM.BulkPrice =  10000;
ITEM.License =  "T";
ITEM.SuitOnly = true
ITEM.TechOnly = true
ITEM.RaiseCondition = 20
ITEM.W = 1
ITEM.H = 1