ITEM.Name =  "Old Blanket";
ITEM.Desc =  "An old, ratty blanket. Good for sleeping tight in, but better served ripped apart and used for patchwork.";
ITEM.Model =  "models/kek1ch/item_sleepbag.mdl"
ITEM.Weight =  0.25;
ITEM.FOV =  13;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  2000;
ITEM.License =  "TX";
ITEM.SuitOnly = true
ITEM.RaiseCondition = 5
ITEM.W = 1
ITEM.H = 1