ITEM.Name =  "Set of buckles and holster";
ITEM.Desc =  "A set of two steel belt buckles, a leather strip, and a small pistol holster. Can be assembled into a makeshift leg holster. Might get you somewhere with a small holdout pistol as long as nobody notices the bulge in your pants.";
ITEM.Model =  "models/kek1ch/outfit_waste_light.mdl";
ITEM.Weight =  0.5;
ITEM.License = "TX"
ITEM.RepairCondition = 5
ITEM.SuitOnly = true
ITEM.FOV =  16;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  250;
ITEM.W = 1
ITEM.H = 1
