ITEM.Name =  "Intermediate Sewing Kit";
ITEM.Desc =  "A sewing kit that's been opened but barely used. It'll work well enough for a patch-up job.";
ITEM.Model =  "models/kek1ch/sewing_kit_b.mdl";
ITEM.Weight =  1
ITEM.License = "T"
ITEM.FOV =  10;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 2, -2, 0 );
ITEM.BulkPrice =  15000;
ITEM.License =  "T";
ITEM.SuitOnly = true
ITEM.TechOnly = true
ITEM.RaiseCondition = 30
ITEM.W = 1
ITEM.H = 1