ITEM.Name = "Weapon Parts"
ITEM.Desc = "An assortment of gun parts."
ITEM.Model = "models/kek1ch/waste_large.mdl"
ITEM.Weight = 0.5
ITEM.License = "T"
ITEM.BulkPrice =  12500;
ITEM.RaiseCondition = 15
ITEM.WeaponOnly = true
ITEM.TechOnly = true
ITEM.W = 1
ITEM.H = 1