ITEM.Name =  "Mini Sewing Machine";
ITEM.Desc =  "A portable sewing machine, luckily still intact.";
ITEM.Model =  "models/props_lab/harddrive01.mdl";
ITEM.Weight =  1.5;
ITEM.License = "TX"
ITEM.SuitOnly = true
ITEM.TechOnly = true
ITEM.RepairCondition = 15
ITEM.FOV =  13;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.W = 1
ITEM.H = 1
ITEM.BulkPrice =  7500;