ITEM.Name =  "Soldering Tools";
ITEM.Desc =  "A jumble of assorted soldering tools: irons, tips, flux, and solder.";
ITEM.Model =  "models/z-o-m-b-i-e/ST/technica/st_technica_details_01.mdl";
ITEM.Weight =  1;
ITEM.FOV =  13;
ITEM.CamPos =  Vector( 50, 50, 50 );
ITEM.LookAt =  Vector( 0, 0, 0 );
ITEM.BulkPrice =  7500;
ITEM.RaiseCondition = 15
ITEM.WeaponOnly = true
ITEM.TechOnly = true
ITEM.License = "T"
ITEM.W = 2
ITEM.H = 1